directories:
  output: release/build
  buildResources: assets
  app: release/app
productName: Pixsoffice Albums
appId: com.pixsoffice.albums
asar: true
asarUnpack:
  - '**\*.{node,dll}'
files:
  - filter:
      - dist
      - node_modules
      - package.json
      - '!**/*.md'
      - '!**/*.txt'
      - '!**/*.env'
afterSign: .erb/scripts/notarize.js
mac:
  icon: assets/icons
  target:
    target: default
    arch:
      - arm64
      - x64
  type: distribution
  hardenedRuntime: true
  entitlements: assets/entitlements.mac.plist
  entitlementsInherit: assets/entitlements.mac.plist
  gatekeeperAssess: false
dmg:
  icon: assets/icons
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
win:
  icon: assets/icons
  target:
    - target: nsis
      arch:
        - x64
linux:
  target:
    - AppImage
  category: Development
extraResources:
  - filter:
      - .env
      - ./assets/**
publish:
  provider: github
  owner: DynMatrix
  repo: electron-desktop-repo
electronVersion: 20.3.12
